# gen_doc.py
# Author: Pistack
# Date: 2021. 08. 30.
# Email: pistatex@yonsei.ac.kr
# Part of XAS-pre-fit-pack package
# Generates Document for XASpefitpack packge

from datetime import date

doc_lst = []
f = open('./docs_txt/doc_list.txt', 'r')
for line in f:
    doc_lst.append(line.strip())
f.close()

doc = dict()
f = open('./version.txt', 'r')
doc['version'] = f.read()
f.close()

for d in doc_lst:
    f = open(f'./docs_txt/{d}.txt', 'r')
    doc[d] = f.read()
    f.close()

doc['description'] = doc['description'].format(doc['version'],
                                               doc['structure'])

doc_lst.remove('structure')

info_script = '''# info.py:
# copyright: {} by pistatex (Junho Lee).
# license: LGPL3.
# Automately generated by gen_doc.py

__info__ = dict()

'''

info_script = info_script.format(date.today().year)

for d in doc_lst:
    info_script = info_script + f'__info__[\'{d}\'] = {doc[d]} \n'

f = open('./src/TRXASprefitpack/doc/info.py', 'w')
f.write(info_script)
f.close()
