f = open('./setup.cfg.template', 'r')
template = f.read()
f.close()
f = open('./version.txt', 'r')
version = f.read().replace('\n', '')
f.close()
f = open('./setup.cfg', 'w')
f.write(template.format(version))
f.close()
