# gen_doc.py
# Author: Pistack
# Date: 2021. 08. 30.
# Email: pistatex@yonsei.ac.kr
# Part of XAS-pre-fit-pack package
# Generates Document for XASpefitpack packge

from datetime import date

doc_lst = []
f = open('./docs_txt/doc_list.txt', 'r')
for line in f:
    doc_lst.append(line.strip())
f.close()

doc = dict()
f = open('./version.txt', 'r')
doc['version'] = f.read().replace('\n', '')
f.close()

for d in doc_lst:
    f = open(f'./docs_txt/{d}.txt', 'r')
    doc[d] = f.read()
    f.close()

doc['description'] = doc['description'].format(doc['version'],
                                               doc['structure'])

info_script = '''# info.py:
# copyright: {} by pistatex (Junho Lee).
# license: LGPL3.
# Automately generated by gen_doc.py

class docs:

    \'\'\' class for store the documentation for TRXASprefitpack \'\'\'
    
    def __init__(self):
        self.info = dict()
        return
    
    def appnd(self, name, txt):
        self.info[name] = txt
        return

__info__ = docs()

doc = dict()

'''

info_script = info_script.format(date.today().year)

lst = doc.keys()

for d in doc.keys():
    if d == 'version':
        info_script = info_script + f'doc[\'{d}\'] = \'{doc[d]}\' \n'
    elif d == 'structure':
        continue
    else:
        info_script = info_script + f'doc[\'{d}\'] = {doc[d]} \n'
for d in doc.keys():
    if d != 'structure':
        info_script = info_script + \
            f'__info__.appnd(\'{d}\', doc[\'{d}\']) \n'
    else:
        continue

info_script = info_script + '__info__ = __info__.info' + '\n' + 'del doc'

f = open('./src/TRXASprefitpack/doc/info.py', 'w')
f.write(info_script)
f.close()
